# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cmr <- function(psi, X, n, K, reps) {
    .Call('mumocomp_cmr', PACKAGE = 'mumocomp', psi, X, n, K, reps)
}

